### ISSUE TITLE
Jace's list of changes

### ISSUE THREAD

**Issue by RWParsons** [RWParsons/iTRAQI-analyses#1]
The dev version of the app (new design etc being developed in #2) is here: : <https://aushsi.shinyapps.io/iTRAQI/>. When it has all the functionality of the old iTRAQI app but in the new design and faster, I'll point all references to the iTRAQI app towards this link (and update Susanna's webpage to reference to this instead of the current site).

- [x] ACUTE travel time bands
CONFIMRED: We will go back to using 5 categories for ACUTE CARE time in iTRAQI
1	    < 1
2	    1 – 2
3	    2 – 4
4	   4 – 6
5	   6 +

> completed in adeaee09c930e701028503555adccd6899f33f70

- [x] REHAB travel time bands
CONFIRMED: We will stay with using 3 categories for travel to REHAB in iTRAQI
A	  < 2
B	  2 – 4
C	  4+

> completed in adeaee09c930e701028503555adccd6899f33f70

### **BIG ONE**: move iTRAQI_app into a subdirectory of iTRAQI-anlayses (this repo) and make it as a rhino app with the same renv. It's much too hard to maintain across two repositories as they share a lot of the same data. Need to move to rhino app since it's impossible to look at the old app as it is much too large.

> I put this one into a separate issue: (https://github.com/RWParsons/iTRAQI-analyses/issues/2)

- [x] ASGS version?
[counts by sa level](https://github.com/RWParsons/iTRAQI-analyses/blob/main/output/tables/counts_by_sa_level.csv)
Can I check what ASGS edition you used to produce the table 'Counts_by_sa_level? It doesn’t align with any of the 3 ASGS editions (2011, 2016, 2021) in the downloads (when I do the same crosstabs), so I am confused! (which is very easy for me to get, as you know! Lol!) What do you think is going on here?
![image](https://github.com/RWParsons/iTRAQI-analyses/assets/47549264/2ce7ef76-f1cb-400c-8f8d-265288196721)
> the function I was using to simplify the polygons (`rmapshaper::ms_simplify()`) for use in the app (and I was also using these polygons later in the pipeline for getting some of the tables) was removing some of the very small polygons by default?! I fixed this so that small shapes aren't removed and the totals now add up :) fb8bbc3fd5e17c7bf8e9f675407ad4744100064e (see [here](https://github.com/RWParsons/iTRAQI-analyses/commit/fb8bbc3fd5e17c7bf8e9f675407ad4744100064e#diff-ec906fe7f2572bb4b4515771b380e721f1f02d82a843b267033c844348e94a7d))

- [x] Different totals??
When I summed the total number for the counts_by_remoteness_level and counts_by_seifa_level tables, the final number was 11,818??? Which doesn’t match any of the other SA1 totals (see Q 7 above). Please help, Rex
counts by remoteness and counts by seifa in outputs/tables
![image](https://github.com/RWParsons/iTRAQI-analyses/assets/47549264/a10bfbdf-e412-4aff-9db0-07b90b47a7af)
> I made a bit of a rookie error here and was using the combined data of SA1s and SA2s before! I have corrected it to be using the 2016 SA1s and the counts are now consistent with the other tables (n = 11559) I also renamed the table to make this clear that they're for SA1s. aeb5a86bc5265b2c9a032eeffb21a72ac4e57ada

- [x] Acute and Rehab time maps - [legends](https://github.com/RWParsons/iTRAQI-analyses/tree/main/output/figures)
Can I confirm what the shading refers to for the new Acute and Rehab maps? 
Given the additions made to the acute care times, I think it probably makes sense now that the lighest colour is < 1 hr? I would find it easier, too, if the legend was presented as hours (see scratchy markup below!) Is this ‘easy’ to do?
![image](https://github.com/RWParsons/iTRAQI-analyses/assets/47549264/e7982f92-0661-40be-b0f9-d8b3d2bc4bbb)

> In the remade app, since I've been using a continuous colour scheme for the maps, I have changed the legend to be continuous as well rather than the categorised time like in the picture.

- [x] update continuous legend to be in the same order (top-down, increasing) as other legends on app and static maps 0ac2c6fe9e9584499983ecdaba71e7b6a608ce86

- [x] update colour scheme as per email from Susanna - 
1A	 	255	230	153
2A	 	255	191	47
3A	 	255	136	83
3B	 	255	110	36
3C	 	255	78	19
4A	 	230	60	66
4B	 	220	30	72
4C	 	196	0	78
5B	 	140	0	78
5C	 	95	0	78
cc2df63ea92c5cd2d4fbb3c5f20a1930a533549f

- [x] All acute time, rehab time and iTRAQI maps
Is it also possible to add a scale to these maps? Adam thought this would be a good way to make sure the reader (of the publication/tech report) doesn’t lose sight of the sheer size of QLD! 0e04bbdec334107ce9af5556708318e2baa07eaf

- [x] Rehab-time-max SA2
Looks like black is still being used as the last colour in the palette for the continuous maps? (I esp saw this in the rehab-time-max SA2 map). Are you able to make the last colour the dark purple as you have done for the iTRAQI maps? 49c1d0b3860599ed569667108d7ddeaa1fb7cffe

- [x] Combining RSQ fixed wing and helicopter locations
Are you able to produce one figure with both FW and Helo icons included on the same map, please?
![image](https://github.com/RWParsons/iTRAQI-analyses/assets/47549264/a26b4069-02d0-476e-9eae-61a2569384da)
a075ef2d63085a3e000945151928a7089d76d327 new figure [here](https://github.com/RWParsons/iTRAQI-analyses/blob/main/output/figures/rsq-helicopter_and_fixed-wing_locations.jpeg)

- [x] Rehab serves maps (insert and combined)
Given we have removed any talk of gold/silver rehab centres, can we please change the icon on the two maps to be dark green crosses for the 5 rehab centres? (i.e. same marker you’ve used on the ‘Major-and-regional rehab services’ map, but dark green instead of red, please). 
![image](https://github.com/RWParsons/iTRAQI-analyses/assets/47549264/6afd578b-c0c5-4e88-82fc-5b1a435b642d)
33e8c65a810420601474f9f4dd7174983bde9bb7

- [x] Continuous_legend.jpeg
Is it possible to make the continuous legend be a little more ‘fine grained’, so that it has a tick mark/label every 2 hours?
ab491bfc785ed0011d132f80c1a2d8a9c86aca64 I've made it taller and more detailed (every 2 hours).
[see new version here](https://github.com/RWParsons/iTRAQI-analyses/blob/main/output/figures/continuous_legend.jpeg)

- [x] SEIFA 2021
SEIFA download is now available for ASGS 2021 – can we please add a SEIFA tab to the Excel downloads for ASGS 2021 too please? Socio-Economic Indexes for Areas (SEIFA), Australia, 2021 | Australian Bureau of Statistics (abs.gov.au) [link](https://www.abs.gov.au/statistics/people/people-and-communities/socio-economic-indexes-areas-seifa-australia/latest-release)
a8c4fbfea9dd4fbcd0260eb3e7fd27d77f6ddfa5

- [x] Remoteness Areas 2021 
RA download is now available for ASGS 2021 – can we please add a RA tab to the Excel downloads for ASGS 2021 too please?
 **NOTE: I can’t find an SA2 to RA allocation file though?!?! (Only SA1 to RA for 2021 ASGS - see link below). My memory is in the past, this correspondence was produced, and if more than 1 RA was present for the SA1s that made up the SA2, ABS would use a percentage to indicate the amount that each RA contributed to a particular SA2, and it was up to the researcher/user to create the SA2 to RA correspondence??? You and @cramb would prob know more about it! Anyways, I think it would be good to add the Remoteness area to the 2021 SA1 download in any case if ABS hasn’t produced the SA2 to RA correspondence.
**UPDATE 9 MAY: Susanna will develop lookup table for SA2 to RA correspondance for 2021**
[link](https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/allocation-files)
> a8c4fbfea9dd4fbcd0260eb3e7fd27d77f6ddfa5 have updated with placeholder data while I wait to get the new data from Susanna
> b51b6e647c26f80cd7cff9a36098e00bda5a28d2 have updated with the data from Susanna 🚀 

- [x] Tour -> Queensland
Change Aeromedical bases (n = 13) to Aeromedical locations (n = 13) 
364dc303247beaabffdb47eac8853bac328b2cb8

- [x] Tour -> Building iTRAQI - visualising access to rehabilitation
Because we no longer have 'step down' rehab locations, the text for the ‘visualising access to rehabilitation’ tab needs to be amended. To keep it more simple now, I think we can write: “There are five rehabilitation units in Queensland public hospitals where TBI patients can receive specific brain injury rehabilitation following their acute care. Rehabilitation time is calculated as the time it takes to drive from each locality (*insert blue dot*) to the closest public, in-patient rehabilitation unit (*insert green cross*). These were calculated using road networks and off-peak driving conditions using ArcGIS Online. These travel times were then interpolated to provide coverage for all of Queensland. CLICK on a rehabilitation destination for facility details.” (Please correct me if I’m wrong, Rex!!!) 8962f5edf89eb91eab8587c941323f75a9d5d6cb

- [x] Removing 'Step-down rehab care destination' from pop-up boxes for localities
Because we no longer have 'step down' rehab locations, we need to change the pop-up boxes for the localities to remove the ‘step-down rehab care destination’ 
![image](https://github.com/RWParsons/iTRAQI-analyses/assets/47549264/cd1ea728-5e3c-4a3e-be2d-f80131d8fd85)179eaec5c054e00a4a8a9c65bbc473a549f4ada5

- [x] Tour -> Building iTRAQI - aggregation into categories
Just popping this here as a reminder to update categories here. Also, please change subheadings to be ‘Time to Acute Care’ and ‘Time to Rehabilitation Care’. 8d06c4497c464252d96900d26d0242a6224a1e7a

- [x] Information -> Suggested citation
UPDATE TO:
Jamieson Trauma Institute, Retrieval Services Queensland and Queensland University of Technology, 2024. iTRAQI: injury Treatment & Rehabilitation Accessibility Queensland Index, version 2.0. Available from: https://access.healthequity.link/ Accessed [date] b7013b256db37f5f07c480dbae5a44eb0b756941

- [x] Information -> About
UPDATE TO:
iTRAQI (injury Treatment and Rehabilitation Accessibility Queensland Index) allows users to explore the average travel times to acute care for moderate-to-severe traumatic brain injuries under ideal but realistic scenarios, as well as one-way driving time to public, in-patient rehabilitation facilities.
Users can:
•	Predict travel time from any location in Queensland.
•	Discover the routes taken to get to acute care for 441 specific locations
•	Explore how travel times interact with remoteness and socioeconomic status for small regions through filtering.
•	Download estimates by small regions for census year boundaries (2011, 2016 and 2021).
•	Learn more through the interactive tour.
iTRAQI is a collaborative project involving the Jamieson Trauma Institute (JTI), Queensland University of Technology (QUT) and representatives from Queensland Ambulance Service (QAS) and Retrieval Services Queensland (RSQ), supported by the Australian Research Council through the ARC Centre of Excellence for Mathematical and Statistical Frontiers (ACEMS), QUT’s Centre for Data Science, and the Emergency Medicine Foundation, with additional input from government, community members and clinicians. c77e314ead958376ecb72809cad5c24aa9c21510

- [x] Information -> Using the site -> Downloads 9b3230efb35f23facd408e69264a6d8d8aff8b78
UPDATE TO:
Here you can download excel files that contain aggregated travel time to both acute and rehabilitation care separately, along with the iTRAQI index, for each statistical area level 1 and 2 (SA1 and SA2). They also include correspondence with the Socio-Economic Indexes for Areas (SEIFA) quintiles and the five remoteness areas (based on the Accessibility/Remoteness Index of Australia).
These are available for the 2011, 2016 and 2021 editions of the Australian Statistical Geography Standard (ASGS). See https://maps.abs.gov.au/ to compare geographic boundaries under different editions. The interactive maps displayed in this site use the 2016 ASGS SA1 and SA2 boundaries.
If the download button downloads an html file initially, check that the tab you were previously on has loaded properly and then re-try

- [x] Information -> Methods fa015eebc2a2628931326ec330498a9360db9efe
UPDATE TO:
For 441 locations, travel time was calculated to acute care, and one-way driving time to rehabilitation units. These were interpolated using ordinary kriging to cover all of Queensland as a continuous measure. The median, maximum and minimum times were then calculated for the commonly used geographic boundaries of statistical areas 1 and statistical areas 2 (under the Australian Statistical Geography Standard). The maps display the 2016 ASGS boundaries, but downloads are also available for 2011 and 2021 boundaries.

Time to rehabilitation care Based on driving times, calculated using ArcGIS Online, using established speed limits and road networks, and using ‘off-peak’ traffic conditions.

TIme to acute care
This was a mix of air and road retrievals, as would be considered in practice.
Road transport assumptions:
1. Patient assumed to have met the Queensland Ambulance Service, pre-hospital trauma by-pass guideline.
2. One hour road transport boundaries calculated using off-peak and non-emergency driving conditions.
3. Response to an acute incident location has the following assumptions:
-  All locations include a 15-minute coordination time (irrespective of response organisation or platform). This accounts for:
1. National Triple Zero (000) call routing to the ambulance service in Queensland;
2. Time for an Emergency Medical Dispatcher to answer the call;
3. Triple Zero (000) call-taking procedure and/or RSQ coordination;
4. Dispatch of primary ambulance or aeromedical platform (i.e. notification of responding platform/service);
5. Time for health professionals to respond (i.e. receive an alert, walk to the ambulance/platform, set up navigation, etc.); and
6. Up to 10 minutes of road travel time.
- Where ArcGIS Pro calculated an ambulance road transport time of greater than 10 minutes, the additional travel (beyond 10 minutes) time was included (i.e. if the total travel time to an incident was 15 minutes, 5 minutes travel time was added to point 3.a).
4. Transport destination assumptions:
a. Directly transport to a major trauma service (also referred to as a ‘neurosurgical centre’ in the case of moderate-severe TBI) if road transport time is within 60 minutes.
b. If greater than 60 minutes road transport time to a major trauma service, transport to the highest-level regional trauma service if within 60 minutes.
c. If greater than 60 minutes road transport from a major or regional trauma service, transport to the closest hospital. In the event this occurs, immediately notify Retrieval Services Queensland.
5. Every road ambulance response was assigned 20 minutes of time on-scene for paramedics to assess, manage and extricate the patient.
6. Limited consideration given to pre-hospital and aeromedical expertise where the incident occurred at the one-hour road drive time boundary of a major or regional trauma service.
7. Road transport time was included only if the initial destination was a regional or major trauma service.
 
Aeromedical transport assumptions:
1. An aeromedical response (fixed wing, rotary wing, or a combination) is available at the closest home base, with no duty hours or weather restrictions, based on current aircraft locations and types.
2. Transport as rapidly as possible to either Brisbane, Gold Coast or Townsville airports for fixed wing responses, or PAH, RBWH, GCUH or TUH for rotary wing responses.
a. The in-flight time for each aeromedical leg was provided by RFDS or the RSQ Rotary Advisor, based on aircraft type at each base and calculated times based on direct flight paths
3. Standardised response times were estimated by one of the investigators (CG) and validated by consensus opinion from other senior medical staff at RSQ. These included:
a. Coordination and tasking by RSQ (see 3a above under ‘Road transport assumptions)
b. Response times by aeromedical teams [rotary wing (15 minutes) and fixed wing (60 minutes)]
c. Standardised on-scene times [rotary wing (60 minutes) and fixed wing (120 minutes)]
d. Where a patient was initially transported to a regional trauma service, 120 minutes was added to the patient journey. This time allows for initial triage, assessment and management of the patient at the regional trauma service prior to transport to a major trauma service
4. No restrictions to destination facilities, such as access block.

- [x] Information -> List of Symbols 6eb7dc38aac05db531756202bd3e7d06c90c6dcb
Change Aeromedical bases (n = 13) to Aeromedical locations (n = 13)
> I made the same change in the markers selection on the main map too

- [x] Information -> Resources b8c8a01a1e97ad7bc4c54defdac9bfad2b88fe9a
Link to Technical Report appears broken?

- [x] Add a year to iTRAQI to orientate the user to the services that were in place at that time (especially since some RFDS assets were upgraded in 2024. Suggest using: iTRAQI: injury Treatment & Rehabilitation Accessibility Queensland Index, 2023, Version 2.0. 5d13caae1ff208a29f4560541d0cf124f5a0c38f

- [x] update hex with new figure image a1e638d2d7c2473c961282c369dd8ca1adf42883

**Comment by jacellewarren** [comment]
iTRAQI team meeting 06/06/24 - Tasks to add to list of changes #1:

1. Once you have finalised the issues #2 , can you please prioritize the changes relating to 1) _ASGS version?_ and 2) _Different Totals?_ from the current list? I want to wait until the numbers are reviewed before finalising the results in the Publication (looking to finalise the publication in next month or so)
2. Add a year to iTRAQI to orientate the user to the services that were in place at that time (especially since some RFDS assets were upgraded in 2024. Suggest using:  _iTRAQI: injury Treatment & Rehabilitation Accessibility Queensland Index, Version 2.0-2023_.
3. Review 'fun facts' that appear during loading of the maps. Susanna suggested we keep these, even if loading is faster, but one of them is Julia falling over.... do you want this one to still be part of the rolling fun facts?

**Comment by RWParsons** [comment]
Hi @jacellewarren!

> 1. Once you have finalised the issues https://github.com/RWParsons/iTRAQI-analyses/issues/2 , can you please prioritize the changes relating to 1) ASGS version? and 2) Different Totals? from the current list? I want to wait until the numbers are reviewed before finalising the results in the Publication (looking to finalise the publication in next month or so)

Sounds good - I've reordered the checklist above.

> 2. Add a year to iTRAQI to orientate the user to the services that were in place at that time (especially since some RFDS assets were upgraded in 2024. Suggest using: iTRAQI: injury Treatment & Rehabilitation Accessibility Queensland Index, Version 2.0-2023.

Easy - added to the list above.

> 3. Review 'fun facts' that appear during loading of the maps. Susanna suggested we keep these, even if loading is faster, but one of them is Julia falling over.... do you want this one to still be part of the rolling fun facts?

haha yeah no worries. I don't think she will mind to be honest but I will check with her/remove it.

**Comment by jacellewarren** [comment]
Hi @RWParsons 

> > 1. Once you have finalised the issues [App redesign - change to leafgl and rhino #2](https://github.com/RWParsons/iTRAQI-analyses/issues/2) , can you please prioritize the changes relating to 1) ASGS version? and 2) Different Totals? from the current list? I want to wait until the numbers are reviewed before finalising the results in the Publication (looking to finalise the publication in next month or so)

Sounds good - I've reordered the checklist above.
Thanks!
> 
> > 2. Add a year to iTRAQI to orientate the user to the services that were in place at that time (especially since some RFDS assets were upgraded in 2024. Suggest using: iTRAQI: injury Treatment & Rehabilitation Accessibility Queensland Index, Version 2.0-2023.
> 
Easy - added to the list above.
You're da best!
> 
> > 3. Review 'fun facts' that appear during loading of the maps. Susanna suggested we keep these, even if loading is faster, but one of them is Julia falling over.... do you want this one to still be part of the rolling fun facts?
> 
haha yeah no worries. I don't think she will mind to be honest but I will check with her/remove it
I didn't even know it was Julia before Susanna told me lol!!!

**Comment by cramb** [comment]
Thanks Rex (and Jace)!

Wondered if even possible to switch order for year added (under point 2) so it becomes iTRAQI 2023 version 2.0? (It’s a minor thing, but thought it might be clearer this refers to a year!)

Super appreciate all your work on this!

Warmly,
Susanna

**Comment by RWParsons** [comment]
> Thanks Rex (and Jace)!
> 
> Wondered if even possible to switch order for year added (under point 2) so it becomes iTRAQI 2023 version 2.0? (It’s a minor thing, but thought it might be clearer this refers to a year!)
> 
> Super appreciate all your work on this!
> 
> Warmly,
> Susanna

No worries, @cramb, have edited in the checklist above. Eventual change will be to:
"iTRAQI: injury Treatment & Rehabilitation Accessibility Queensland Index, 2023, Version 2.0."

**Comment by cramb** [comment]
Amazing! Thank you!

**Comment by RWParsons** [comment]
Hey @jacellewarren ,

> - [ ] Information -> Resources
> Link to Technical Report appears broken?

I didn't change anything for the technical report link but it seems to work for me. Can you check that it still doesn't work for you?

Hey @cramb,
> UPDATE 9 MAY: Susanna will develop lookup table for SA2 to RA correspondance for 2021

Also, @cramb, I have the app to include the remoteness data for the 2021 edition of the ASGS but am just using placeholder data at the moment - can you please let me know if you have a lookup table for me to use here?

**Comment by cramb** [comment]
Thanks Rex! I will get the lookup table to you today – I started on this last Saturday but ran out of time!

Warmly,
Susanna

**Comment by cramb** [comment]
…and please find the Stata dataset attached – if you need a simpler version/have any Qs, just reach out!

(I also have the corresponding Stata dataset for the SA1s, but expect you’ve already pulled the data yourself.)

Thanks for your patience!

Warmly,
Susanna

**Comment by jacellewarren** [comment]
Hey Rex,
Maybe its Queensland Health firewall being difficult again, but when I click on the link for the Tech report under the Information Tab, I get the attached error
![Picture1](https://github.com/RWParsons/iTRAQI-analyses/assets/137136717/c6c56d12-8526-4d6b-ad28-16d2a0fc873e)
I'll ask some QH and non-QH people to try and open the link and see what happens lol - a good ol observational study! Will let you know! :)

**Comment by RWParsons** [comment]
@jacellewarren 

Ohhhh I see. I have always been opening it in a new tab but when I left click it to open it, I get the same issue. (Also, I am using the dev version of the app (<https://aushsi.shinyapps.io/iTRAQI/>) - the one at Susanna's site currenly shows the old version of the app)

**Comment by jacellewarren** [comment]
> @jacellewarren
> 
> Ohhhh I see. I have always been opening it in a new tab but when I left click it to open it, I get the same issue. (Also, I am using the dev version of the app (https://aushsi.shinyapps.io/iTRAQI/) - the one at Susanna's site currenly shows the old version of the app)

Ah ok - my observational study is on hold.... haha! Thanks for the link to the dev version - I better save that in my favourites!

P.s I just flicked through the dev site - it is super fast! Love it!

**Comment by RWParsons** [comment]
@jacellewarren 

haha yeah you're off the hook for the study recruitment 😆. I think I've just fixed it now by forcing all the links to open in a new tab - can you please check that it works for you on the dev site?

**Comment by cramb** [comment]
[heart]         Susanna Cramb reacted to your message:
________________________________

**Comment by RWParsons** [comment]
Hi @cramb @jacellewarren,

I've removed the software change from being a checklist item on this issue (as I moved that to being a separate issue and checklist - #2) and have finished off all other items on this original list. 

I'm closing this issue but if there are any other things that come to mind, please let me know! If they're app related, you can leave a comment on that issue (#2) and if they're related to other content like data or outputs for the report/manuscript, email me and I'll make another issue for them 😄 


🚀 🚀 🚀

**Comment by cramb** [comment]
[celebrate]     Susanna Cramb reacted to your message:
________________________________

**Comment by jacellewarren** [comment]
Yep, works for me from the dev site! Thanks Rex!

**Comment by jacellewarren** [comment]
Thanks Rex!!
