### ISSUE TITLE
App redesign - change to leafgl and rhino

### ISSUE THREAD

**Issue by RWParsons** [RWParsons/iTRAQI-analyses#2]
To expand on the following point in Jace's list: 

> [ ] BIG ONE: move iTRAQI_app into a subdirectory of iTRAQI-anlayses (this repo) and make it as a rhino app with the same renv. It's much too hard to maintain across two repositories as they share a lot of the same data. Need to move to rhino app since it's impossible to look at the old app as it is much too large.

- [x] use rhino framework
- [x] use outputs from analyses pipeline
- [x] recreate maps tab using leafgl
  - [x] layer selection
    - [x] polygons 989275ffc229ab3762b15c12075975f682e6467d
    - [x] make transition between displayed shapes faster by adding new layer before a show and then hide/remove old layer bf1a1e95bce6be0179665798ea4893c203006b83
    - [x] popups on polygons be8bdd89b1352af12213b42abb140d6e19744688
    - [x] rasters 63967ada42441681038a0001402b7c50c6e1ab89
    - [x] add legends f91cdc6e56c5fa6f1435436ae8ecb101d72aef9e
  - [x] filters dc0d8d7940be5b1d7f389498665f06c12395b7eb
  - [x] complete base map with RSQ/aero/centre icons 99f3e958115e16355487dc3831a91c72a85efbca
  - [x] interactive plot
    - [x] base plot that's reactive to 'show plot' checkbox 1365e9d51aaacdcc4fbdcd763e47d4d2fd6a1e1a
    - [x] visibility of points dependent on filters ae4193b8e3a42b5a28195e6f1578dd34998a6fc8
    - [x] colour scales on plot dependent on layer selected (acute/rehab/index) 74510c1c97f1fda7e44970dbe07737b0e4c6f7e1
    - [x] hide 'show_plot' button if selected layer is not a polygon 72be0973cecd22e64f5247a01de31bf5829e49b8
    - [x] implement brush and click interactivity to the plot/map b524bd7ebce28b87bd9e86718f4d12e1926f2314
  - [x] time-to-care prediction from map click 
    - [x] make new marker with predicted acute/rehab time in popup cb31b6cb6dd5bff13821f8c634609a6b02b99610
    - [x] automatically trigger popup to appear shortly after marker is added a63d43c6105eb8b52928fae8cbb55530b7c86e13
    - [x] remove prediction marker when marker is clicked db713fb489dd627fd30fd14bf35e21bddf149051
  - [x] add spinner/waiter with fun fact(oid)s eddc5d9c14a6cf9269600df82e9b1265aa9f71cf
- [x] recreate tour tab using leafgl
  - [x] create structure for progressing/regressing through tour 3abeaa591449c7d7f8e2bdcbabfab0c0761739a4
  - [x] associated card content with the tour stage 13b07ff262059029576b8204014d65a8741eb93c
  - [x] associated map content with the tour stage c0d67d38c4a42e92678ea611796e663c7035db29
  - [x] incorporate map view/panning with tour stages 42ed505659ac6036e92018f023e61b20c85502fa
- [x] recreate info tab 13133356b3e0ca794886d15f67330d3815084495
- [x] recreate downloads tab bf09223d9cfff33687bef3965db5c4347ea36324
- [x] replace rhino logo with an iTRAQI logo 25b249368cb73aa68700cd8dc564ca26573f75b1

misc. features/changes/bug fixes
- [x] update marker popup text from within pipeline 179eaec5c054e00a4a8a9c65bbc473a549f4ada5
- [x] check that the user hasn't changed tour tab before the delayed map pan occurs fb83a481e889256a5828f1177f0bfdfe2d66312e
- [x] add linters <https://www.appsilon.com/post/box-linters-in-rhino-1-8-0> fd6ea0f7722323adb40201913a41dd366dbec036
- [x] output all app inputs straight into app directories to replace the update-data.R script a206670ff518c891b9a99374269cc28fe4feef49
- [x] fix the (lack of) appearance of acute/rehab raster layer on tour da65cdd3b09f5c8f2a758e0fc0ce7b7feb4ad1be
- [ ] need to be able to change the map popups on shapes to be labels so that the map_click event can trigger the creation of a prediction marker and it's popup, not the display of the shape popup. Following the recent developments on leafgl for this here: https://github.com/r-spatial/leafgl/issues/78
  - [ ] wait for the above PR to get accepted and merged into leafgl.
  - [ ] change what are currently polygon popups to be labels (hover, rather than click to show)
  - [ ] adjust the z-index of markers/labels/layers etc so that order is correct and center markers don't appear above polygon popups/labels
  - [ ] ensure that prediction markers work as expected and aren't hidden behind polygon labels
- [x] avoid rsq and qas markers appearing on map load when not default tab 974b29a906973e3eaab0eb5fbc7641fd0a270738
- [x] put markers at higher z-index than polygons ae04bc7bcdb495953794795b559026d07bd9e144
- [x] produce empty map without error when filter removes all polygons from map 9b03e02cf153bd184cd926e7d1f46c345262f959

**Comment by jacellewarren** [comment]
Thanks for this list too, Rex!

**Comment by RWParsons** [comment]
Closing this issue as it seems that the changes in leafgl are taking ages to happen and mapgl looks like a potentially better option.  See #4.
